name: Generate Slideshow from PDF URL

on:
  workflow_dispatch:
    inputs:
      pdfUrl:
        description: 'URL of the PDF file to convert'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build PDF Slideshow from URL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Reveal.js
        uses: actions/checkout@v4
        with:
          repository: hakimel/reveal.js
          path: reveal.js

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils pngquant curl coreutils

      # Rendre les scripts exécutables
      - name: Make scripts executable
        run: |
          chmod +x .github/scripts/process_pdf_url.sh
          chmod +x .github/scripts/generate_main_index.sh

      - name: Prepare Build Directory and Copy Assets
        run: |
          mkdir -p build/dist build/plugin
          cp -r reveal.js/dist/* build/dist/
          cp -r reveal.js/plugin/* build/plugin/
          echo "Build directory structure created and Reveal.js assets copied."

      # Étape 1: Traiter l'URL du PDF fournie
      - name: Process PDF URL using script
        run: .github/scripts/process_pdf_url.sh "${{ github.event.inputs.pdfUrl }}" "build"

      # Étape 2: Générer l'index principal listant les slideshows disponibles
      - name: Generate Main Index HTML using script
        run: .github/scripts/generate_main_index.sh "build"

      # Télécharger l'artefact pour GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
