name: Generate Slideshow from PDF URL or Local Folder

on:
  workflow_dispatch:
    inputs:
      pdfUrl:
        description: 'URL of the PDF file to convert (laisser vide si traitement local)'
        required: false
        type: string
  push:
    branches:
      - main
    paths:
      - 'pdf/**.pdf'
      - '.github/workflows/pdf-slideshow.yml'
      - '.github/scripts/**.sh'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build PDF Slideshow(s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Reveal.js
        uses: actions/checkout@v4
        with:
          repository: hakimel/reveal.js
          path: reveal.js

      # --- Configuration du Cache ---
      - name: Configure Cache Path
        id: cache-path
        run: echo "path=build" >> $GITHUB_OUTPUT # Dossier à mettre en cache

      - name: Restore Build Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.cache-path.outputs.path }}
          # Clé basée sur le runner et un hash des scripts (pour invalider si les scripts changent)
          key: ${{ runner.os }}-build-${{ hashFiles('.github/scripts/**.sh') }}
          # Clés de restauration (facultatif, pour utiliser un cache légèrement plus ancien)
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils pngquant curl coreutils findutils

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Prepare Build Directory and Copy Assets
        # Crée la structure même si le cache est restauré (au cas où)
        run: |
          mkdir -p build/dist build/plugin
          cp -r reveal.js/dist/* build/dist/
          cp -r reveal.js/plugin/* build/plugin/
          echo "Build directory structure created/ensured and Reveal.js assets copied."

      # === Logique conditionnelle de traitement ===

      - name: Process PDF URL (if specified)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.pdfUrl != ''
        run: .github/scripts/process_pdf_url.sh "${{ github.event.inputs.pdfUrl }}" "build"

      - name: Process Local PDF Files (on push)
        if: github.event_name == 'push'
        run: |
          PDF_DIR="pdf"
          BUILD_DIR="build"
          shopt -s nullglob
          files=("$PDF_DIR"/*.pdf)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No PDF files found in $PDF_DIR. Nothing to process."
          else
            echo "Found ${#files[@]} PDF file(s) in $PDF_DIR. Processing..."
            for pdf_file in "${files[@]}"; do
              echo "--- Processing '$pdf_file' ---"
              # Utiliser des guillemets autour du nom de fichier
              .github/scripts/process_local_pdf.sh "$pdf_file" "$BUILD_DIR"
              echo "--- Finished '$pdf_file' ---"
            done
          fi

      # === Fin de la logique conditionnelle ===

      - name: Generate Main Index HTML
        run: .github/scripts/generate_main_index.sh "build"

      # --- Sauvegarde du Cache ---
      # Sauvegarde seulement si quelque chose a changé (ou si nouveau)
      - name: Save Build Cache
        uses: actions/cache/save@v4
        # Condition: exécute seulement si le cache n'a pas été restauré exactement (cache-hit est faux)
        # ou si la clé de restauration exacte n'a pas été trouvée.
        # Ceci évite de sauvegarder si rien n'a changé et que le cache était parfait.
        # Note: La logique exacte peut varier selon les besoins précis de mise à jour du cache.
        # Sauvegarder toujours est plus simple mais peut consommer plus de stockage/temps.
        # if: steps.cache-restore.outputs.cache-hit != 'true' # Option pour ne sauvegarder que si nouveau/modifié
        with:
          path: ${{ steps.cache-path.outputs.path }}
          key: ${{ steps.cache-restore.outputs.cache-primary-key || format('{0}-build-{1}', runner.os, hashFiles('.github/scripts/**.sh')) }} # Utilise la clé restaurée si possible

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
